### ISSUE TITLE
Pass association/batch_key to query function 

### ISSUE THREAD

**Issue by Un3qual** [absinthe-graphql/dataloader#108]
Would it be possible to add the association name to the options passed to the query function when using a custom query?
For example:
```elixir
Dataloader.load(loader, Post, :replies, post)
```
would pass `%{assoc_name: :replies}` or something similar to the opts parameter in the query function.

**Comment by benwilson512** [comment]
@Un3qual can you elaborate on your use case?

**Comment by Un3qual** [comment]
It would be useful to easily be able to have different behavior for the query function depending on which association I'm loading.

**Comment by benwilson512** [comment]
It's a lot less fragile if instead the options are passed in directly:

```
Dataloader.load(loader, Post, {:replies, %{some_option: true}}, post)
```
