### ISSUE TITLE
Unable to find item [\"4039624a-9b02-448d-8158-0db13da76efb\"] in batch

### ISSUE THREAD

**Issue by MeterSoft** [absinthe-graphql/dataloader#111]
why this error can produced? it happened when we use big graph query with connections?

**Comment by benwilson512** [comment]
Hi @MeterSoft, this means that you are calling `Dataloader.get` for an item that is not loaded. For general questions and support though please see the ElixirForum or Slack.

**Comment by Paryz** [comment]
@MeterSoft is your struct names `%Connection{}` I recently started having the same problem with struct that was called this way
