### ISSUE TITLE
Map.t() dialyzer issue

### ISSUE THREAD

**Issue by kyleVsteger** [absinthe-graphql/dataloader#113]
https://github.com/absinthe-graphql/dataloader/blob/master/lib/dataloader/ecto.ex#L281

Can this be changes from `Map.t()` -> `map()`?
I pulled down the repo but could not push a branch upstream.
Thanks!

**Comment by benwilson512** [comment]
Yeah you'd have to push a branch to your own fork, and then do a pull request. Definitely worth it for future things but I'll go ahead and just handle this.
