### ISSUE TITLE
Accessing values from the context and passing in as argument

### ISSUE THREAD

**Issue by morgz** [absinthe-graphql/dataloader#117]
I'm trying to filter an objects association with the id of my current user which I put in the **context** via middleware.  

I am trying to find, and failing, a way to pass this to the dataloader method I have setup in the context.

```elixir
  def query(UserExerciseFavourite, args) do
    # I want the user id in args
    #...
  end
```

I can pass arguments this way:
```elixir
object :exercise do
    # I can pass arguments this way
    field :user_exercise_favourites, list_of(:user_exercise_favourite) do
      resolve(dataloader(Exercises, :user_exercise_favourites, args: %{foo: "bar"}))
    end
end
```

And I can access the id this way, but I can't find the way to then pass it to the method like I can above!
```elixir
    field :user_exercise_favourites, list_of(:user_exercise_favourite) do
      resolve fn exercise, _, %{context: %{loader: loader} = context} ->
        user_id = context |> Map.get(:current_user)
        Logger.debug("\n\n User: #{inspect user_id}\n\n")
        # How can I take my user out of the context and pass to the Dataloader?
        loader
        |> on_load(fn loader ->
          {:ok, Dataloader.load(loader, Exercises, :user_exercise_favourites, exercise)}
        end)
      end
    end
```

Any tips please!

**Comment by benwilson512** [comment]
My @morgz, the best way to do this is actually at the point where you initialize the dataloader instance itself. See `default_params` in https://hexdocs.pm/dataloader/Dataloader.Ecto.html#content.

However you could also pass them in by doing `load(loader, Exercises, {:user_excercise_favorites, %{current_user: user}}, exercise)`
