### ISSUE TITLE
Badmatch error when child have limit and offset and parent have composite primary keys

### ISSUE THREAD

**Issue by jotaviobiondo** [absinthe-graphql/dataloader#124]
When we have a limit and offset in a child queryable of a parent that have composite primary keys, we get a `badmatch` exception because of this: https://github.com/absinthe-graphql/dataloader/blob/19345b4b9dd349b99f8338c4b3ae902a5b035995/lib/dataloader/ecto.ex#L688

I'm happy to help with a PR, I'm just no sure what is the best way to use the primary keys in the `where` clause below to get the results:

https://github.com/absinthe-graphql/dataloader/blob/19345b4b9dd349b99f8338c4b3ae902a5b035995/lib/dataloader/ecto.ex#L706

Any ideas?

**Comment by benwilson512** [comment]
Hey @jotaviobiondo. Unfortunately I'm not sure about the best way to support composite keys, it is intentionally not supported yet within Dataloader. You are welcome to contribute this feature, but it is not on the roadmap at this time.

**Comment by gosseti** [comment]
@jotaviobiondo I’m currently running into the same issue — did you ever find a solution for this?

I’m using this ecto PR branch which has added support for composite primary keys: https://github.com/elixir-ecto/ecto/pull/3638, however running into the same issues with dataloader as you are.

**Comment by jotaviobiondo** [comment]
Hey @gosseti! Unfortunately didn't find a solution other than making a PR (but couldn't make due to lack of time)

For my case, I actually noticed that I didn't need a limit/offset, so problem solved hahah

But good to know there's a PR on the ecto side, so the integration with dataloader will be simpler after the feature is merged 😄
