### ISSUE TITLE
New release planned?

### ISSUE THREAD

**Issue by follmann** [absinthe-graphql/dataloader#128]
Hi all,

we were just wondering if a new release is planned that includes all features and fixes that have been merged since `1.0.8` from August 2020. We rely on some of our contributions and others and I'd be great to have a specific version locked again instead of pointing to master.

Thanks!

**Comment by the-destro** [comment]
+1 as cutting a release will also pull in a dialyzer fix I am being bitten by: #114

**Comment by jadlr** [comment]
@benwilson512 any news on this? We're still running with our own fork.

**Comment by benwilson512** [comment]
Done.

**Comment by tlvenn** [comment]
Thanks @benwilson512 !
