### ISSUE TITLE
Error when used in transactions

### ISSUE THREAD

**Issue by arnodirlam** [absinthe-graphql/dataloader#129]
Hi there,

we're using Dataloader without Absinthe and came across this error:

> ** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.3039.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 1562ms.

when running the following code in a test:

```elixir
Ecto.Multi.new()
|> Ecto.Multi.run(:whatever, fn _, _ ->
  Dataloader.new()
  |> Dataloader.add_source(:repo, Dataloader.Ecto.new(MyApp.Repo))
  |> Dataloader.load(:repo, :roles, user)
  |> Dataloader.run()
end)
|> Ev2.Repo.transaction()
```

Outside of an `Ecto.Multi`, it works:

```elixir
Dataloader.new()
|> Dataloader.add_source(:repo, Dataloader.Ecto.new(MyApp.Repo))
|> Dataloader.load(:repo, :roles, user)
|> Dataloader.run()
```

Is this something that can and should be fixed in `Dataloader`?

Thanks a lot for this great project! 🙌

**Comment by arnodirlam** [comment]
Tried with

- Dataloader 1.0.8 and master
- Ecto 3.6.2 and master

**Comment by benwilson512** [comment]
Interesting. Dataloader.Ecto explicitly sets the caller value to the pid that calls `load` in order to avoid this issue. A test case which reproduces this would be very helpful if you have time open a PR with one.

**Comment by arnodirlam** [comment]
Turns out it just expects an `:ok` tuple, which we did not return. So this works:

```elixir
Ecto.Multi.new()
|> Ecto.Multi.run(:whatever, fn _, _ ->
  loader =
    Dataloader.new()
    |> Dataloader.add_source(:repo, Dataloader.Ecto.new(MyApp.Repo))
    |> Dataloader.load(:repo, :roles, user)
    |> Dataloader.run()

  {:ok, loader}
end)
|> Ev2.Repo.transaction()
```

Thanks a lot for your time and help! 🙏 Closing this issue..

**Comment by arnodirlam** [comment]
We ran into issues again, now with a correct return value for `Multi.run/3`. Please see my updated [PR branch](https://github.com/absinthe-graphql/dataloader/pull/130).

```
[error] Task #PID<0.938.0> started from #PID<0.936.0> terminating
** (DBConnection.ConnectionError) could not checkout the connection owned by #PID<0.931.0>. When using the sandbox, connections are shared, so this may imply another process is using a connection. Reason: connection not available and request was dropped from queue after 999ms. You can configure how long requests wait in the queue using :queue_target and :queue_interval. See DBConnection.start_link/2 for more information
    (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:593: Ecto.Adapters.SQL.raise_sql_call_error/1
    (ecto_sql 3.4.4) lib/ecto/adapters/sql.ex:526: Ecto.Adapters.SQL.execute/5
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:192: Ecto.Repo.Queryable.execute/4
    (ecto 3.4.5) lib/ecto/repo/queryable.ex:17: Ecto.Repo.Queryable.all/3
    (dataloader 1.0.8) lib/dataloader/ecto.ex:328: Dataloader.Ecto.run_batch/6
    (dataloader 1.0.8) lib/dataloader/ecto.ex:656: Dataloader.Source.Dataloader.Ecto.run_batch/2
    (dataloader 1.0.8) lib/dataloader/ecto.ex:614: anonymous fn/2 in Dataloader.Source.Dataloader.Ecto.run_batches/1
    (elixir 1.12.1) lib/task/supervised.ex:90: Task.Supervised.invoke_mfa/2
    (elixir 1.12.1) lib/task/supervised.ex:35: Task.Supervised.reply/5
    (stdlib 3.15.1) proc_lib.erl:226: :proc_lib.init_p_do_apply/3
Function: &:erlang.apply/2
    Args: [#Function<14.77029692/1 in Dataloader.Source.Dataloader.Ecto.run_batches/1>, [{{:queryable, #PID<0.931.0>, Dataloader.User, :one, :id, %{}}, #MapSet<[{490, 490}]>}]]
```

Grateful for any hints or pointers! 🙏

**Comment by benwilson512** [comment]
@arnodirlam are you able to create an example I can run?

**Comment by arnodirlam** [comment]
@benwilson512 Yes, the tests in the linked PR should fail: #130

**Comment by arnodirlam** [comment]
Thanks a lot for confirming the issue and for coming up with a PR, @giddie 🙏 

I've done more research, and found out the following:

### Why does dataloader use async processes?

Partly for error handling, partly for performance optimization.

The hierarchy of processes looks as follows:

1. A process calls Dataloader
2. A process is spawned for loading all sources (using `Task.async` + `Task.await`) [[Dataloader.run/1](https://github.com/absinthe-graphql/dataloader/blob/91db9e4f3cb8e3b375c997d83e4b1f57f97e3bf7/lib/dataloader.ex#L153-L157)]
3. A process is spawned for each source (using `Task.async_stream`) [[Dataloader.run_tasks/3](https://github.com/absinthe-graphql/dataloader/blob/91db9e4f3cb8e3b375c997d83e4b1f57f97e3bf7/lib/dataloader.ex#L320)]
4. For each source, a process is spawned for loading all batches (using `Task.async` + `Task.await`) [[Dataloader.Ecto.run/1](https://github.com/absinthe-graphql/dataloader/blob/91db9e4f3cb8e3b375c997d83e4b1f57f97e3bf7/lib/dataloader/ecto.ex#L393)]
5. For each source, a process is spawned for each batch (using `Task.async_stream`) [[Dataloader.Ecto.run_batches/1](https://github.com/absinthe-graphql/dataloader/blob/91db9e4f3cb8e3b375c997d83e4b1f57f97e3bf7/lib/dataloader/ecto.ex#L607-L620)]

Spawning 2. and 4. is for catching errors raised while loading sources and batches, respectively. They trap exits ([docs](https://www.erlang.org/doc/man/erlang.html#process_flag_trap_exit)).
Spawning 3. and 5. is for loading sources and batches in parallel. They are also used to enforce timeouts on loading each batch.

### Why doesn't that work with transactions?

A transaction is bound to a DB connection that's held by the process calling Dataloader. DB connections, however, cannot be shared between processes.

> I believe it is not about the sandbox. Transactions are per process, you cannot share a transaction across multiple process. If you have work you want to process in parallel, you can do all of the normalization on the side and leave the final step of inserting the data to the main process.

 -- José Valim on [Ecto mailing list](https://groups.google.com/g/elixir-ecto/c/WhenMB4R3Js/m/7cqLVwfXBAAJ) (Mar 13, 2017)

### How does Ecto itself handle this?

Ecto's preloader checks whether the process it's called from already has a checked out connection. If yes, it does not preload in parallel (using `Task.async_stream`) but synchronously:

```elixir
    if match?([_,_|_], preloaders) and not checked_out?(repo_name) and
         Keyword.get(opts, :in_parallel, true) do
      preloaders
      |> Task.async_stream(&(&1.(opts)), timeout: :infinity)
      |> Enum.map(fn {:ok, assoc} -> assoc end)
    else
      Enum.map(preloaders, &(&1.(opts)))
    end
```
 -- shortened version of the [code in Ecto.Repo.Preloader](https://github.com/elixir-ecto/ecto/blob/b2a2b75067ad9b5b8298ea911053969de1fd93a5/lib/ecto/repo/preloader.ex#L124-L125) introduced by José Valim in [78ba871](https://github.com/elixir-ecto/ecto/commit/78ba8713cf8f505688feac8ce524906cba3eb984)

### How to fix the issue?

By restructuring Dataloader to not spawn processes if it's run from within a transaction. Instead of using `Task.async` for catching errors, we could wrap calls to the data-loading in `try/rescue` blocks. Would that cover all error cases?

In particular, I suggest the following changes (will update according to feedback):

- [ ] Replace uses of `Task.async` by counterparts using `try/rescue` (levels 2. and 4. in process hierarchy)
- [ ] Categorize sources into those that need to be run synchronously (i.e. Ecto sources with a checked out connection) and those that can be run asynchronously. Run the async ones using `Task.async`, then run the synchronous ones sequentially, then `Task.await` all async ones.
- [ ] Load batches synchronously if the source needs to be run synchronously
- [ ] For Ecto sources loading batches synchronously, handle timeouts using the `:timeout` option on Ecto.Repo functions ([docs](https://hexdocs.pm/ecto/3.7.1/Ecto.Repo.html#module-shared-options)) as timeouts aren't enforced anymore by processes spawned using `Task.async_stream`.
- [ ] Optimization: Don't spawn processes to load only a single source or batch (see `Ecto.Repo.Preloader` code above)
- [ ] Optional: Add source option `:in_parallel` to force running in parallel (similar to @giddie's PR #314, but named like in Ecto) - up to you, @giddie 


I know it's quite a bit of refactoring, but I think it's worth it!

Looking forward to feedback and discussion! @giddie @benwilson512 😄

**Comment by arnodirlam** [comment]
Also @seddy who worked on the async parts a lot 👌

**Comment by seddy** [comment]
Don't think you meant me @arnodirlam, though I'm more than happy to take credit for someone else's work obviously :joy_cat:

**Comment by arnodirlam** [comment]
So this wasn't you? @seddy https://github.com/absinthe-graphql/dataloader/commit/ce9ac3f3e4649dd15a3094ad50ba841511455d31 🤔

**Comment by giddie** [comment]
Great work @arnodirlam. Looks like you went a few steps further than me by delving into Ecto to find a better solution and writing it all up :) Your recommendations sound good to me.

**Comment by benwilson512** [comment]
Handled now in 1.0.11. To use, make sure that when you call `Dataloader.new/1` you do:

```
loader = Dataloader.new(async?: !MyApp.Repo.in_transaction?())
```

This will be handled automatically in 2.0
