### ISSUE TITLE
Proposal for a high-level Ecto dataloader

### ISSUE THREAD

**Issue by suzdalnitski** [absinthe-graphql/dataloader#162]
Similar to [Proposal for a high-level declarative Dataloader API](https://github.com/absinthe-graphql/dataloader/issues/161), but this proposal builds on top of the superloader, and is a very neat way to fetch Ecto associations.

In the simplest possible use case, it looks like this:

```elixir
field :user, :user do
  resolve load_field(:user)
end
```

It supports `belongs_to`, `has_one`, `has_many` and `many_to_many` associations.

The only thing a developer has to do, is to make use of the `load_field` resolver function. Internally, it makes use of Ecto schema introspection to load the associations. No need to modify Ecto schemas, or write any other code.

## Some examples
This will fetch the user association on a GraphQL object

```elixir
field :user, :user do
  resolve load_field(:user)
end
```

### Fetch user, and return the name of the fetched user

```elixir
field :user_name,:string do
  resolve load_field(:user, return: {:user, :name})
end
```

### Fetch nested associations

```elixir
field :friend_names, list_of(:string) do
  resolve load_field([user: [friends: :name]], return: {:"user.friends", :name})
end
```

### Apply a transformation, before returning the value from the resolver

```elixir
field :friend_count, :integer do
  resolve load_field([user: :friends], then: %{:"user.friends": friends} -> Enum.count(friends) end)
end
```

### It can even be used to do all sorts of crazy fetches

```elixir
load_fields([
  :name,
  friends: [
    :age,
    posts: :title
  ]
], then: ...)
```

**Comment by benwilson512** [comment]
Hey @suzdalnitski I think this is an interesting idea, but I think my gut reaction to both this and the other proposal is that this would be best implemented as a `SuperLoader` library works with Dataloader. I have definitely wanted to take time to build a more ergonomic API for Dataloader, but I don't have the time right now to make headway on it.

**Comment by suzdalnitski** [comment]
I agree with you, this makes sense, I've closed the issue.

Thanks for your time.
