### ISSUE TITLE
[Ecto] If the assoc is already loaded, we should return it directly

### ISSUE THREAD

**Issue by tlvenn** [absinthe-graphql/dataloader#2]
As discuss with @benwilson512 , the `assoc` macro from absinthe_ecto is checking if the value for the field was already present in the parent in the case that it was preloaded and would simply return it if that is the case.

The Ecto dataloader should mimic this behaviour which is super useful when a field may or may not be preloaded already.

**Comment by tlvenn** [comment]
This has been adressed by @benwilson512 and can be closed.

**Comment by benwilson512** [comment]
Handled by the absinthe dataloader helper.
