### ISSUE TITLE
Dataloader should use MapSet for the ids

### ISSUE THREAD

**Issue by samphilipd** [absinthe-graphql/dataloader#26]
It seems like if we make multiple duplicate loads, dataloader constructs a SQL query with multiple IDs.

For example, we construct a loader like this:

```elixir
loader = loader
|> Dataloader.load(:nest_db, NestDB.BuyerOffer, 290)
|> Dataloader.load(:nest_db, NestDB.BuyerOffer, 290)
|> Dataloader.load(:nest_db, NestDB.BuyerOffer, 290)
```

Now we get a struct like so:

```elixir
%Dataloader{
  options: [],
  sources: %{
    nest_db: %Dataloader.Ecto{
      batches: %{
        {:queryable, #PID<0.1196.0>, NestDB.BuyerOffer, %{}} => [
          {290, 290},
          {290, 290},
          {290, 290}
        ]
      },
      default_params: %{},
      options: [],
      query: #Function<0.77438868/2 in Eggl.Loader.dataloader/0>,
      repo: NestDB.Repo,
      repo_opts: [],
      results: %{}
    }
  }
}
```

Which results in a query that looks like this:

```
...
WHERE (b0."id" = ANY($1)) [[290, 290, 290, 290]]
```

Could we use a Mapset to remove this duplication?

**Comment by axelson** [comment]
I believe this is already added in these PR's:
* Dataloader.KV - https://github.com/absinthe-graphql/dataloader/pull/23
* Dataloader.Ecto - https://github.com/absinthe-graphql/dataloader/pull/20

**Comment by samphilipd** [comment]
Bosh! Love it.

**Comment by benwilson512** [comment]
Handled via previous PRs.
