### ISSUE TITLE
Getting a menu item by ID returns null after 1.0.1

### ISSUE THREAD

**Issue by bossyang** [absinthe-graphql/dataloader#32]
### Environment

-  Elixir version (elixir -v): 1.6.4
-  Absinthe version : 1.4.12
-  dataloader version: `1.0.2`

### Expected behavior
_Craft GraphQL APIs In Elixir_ 
Chap 10, Complex Queries

schema.ex
```elixir
query do
    field :menu_item, :menu_item do
      arg :id, non_null(:id)
      resolve &Resolvers.Menu.get_item/3
    end
```

resolvers/menu.ex
```elixir
defmodule PlateSlateWeb.Resolvers.Menu do
  alias PlateSlate.Menu
  import Absinthe.Resolution.Helpers
  def get_item(_, %{id: id}, %{context: %{loader: loader}}) do
    loader
    |> Dataloader.load(Menu, Menu.Item, id)
    |> on_load(fn loader ->
      {:ok, Dataloader.get(loader, Menu, Menu.Item, id)}
    end)
  end
```
GraphiQL
```graphql
{
  menuItem (id: "1") {
    name
  }
}
```
```json
{
  "data": {
    "menuItem": {
      "name": "Reuben"
    }
  }
}
```

### Actual behavior
It works with *dataloader* `1.0.0` or `1.0.1`.
```json
{
  "data": {
    "menuItem": null
  }
}
```

Sorry to submit an issue here due to the temporary shutdown of Pragmatic Forum.

> The FOSTA-SESTA act of 2017 makes us legally responsible for all content posted here by anyone at any time. This act removes Section 230 Safe Harbor protections.
> We cannot possibly monitor all posts made, in real time, and decide if they break any particular interpretation of a vague and imprecise law. That is logistically ludicrous and philosophically objectionable. Our only option is to remove all access to the forums until the US legislature restores reasonable safe harbor law

**Comment by benwilson512** [comment]
Fixed in 1.0.3
