### ISSUE TITLE
Hexdocs not updated for 1.0.3

### ISSUE THREAD

**Issue by axelson** [absinthe-graphql/dataloader#40]
I only see hexdocs for 1.0.2 and not for 1.0.3: https://hexdocs.pm/dataloader/1.0.3/Dataloader.html is a 404 and https://hexdocs.pm/dataloader/Dataloader.html shows the 1.0.2 docs.

**Comment by benwilson512** [comment]
Ah that's just because 1.0.3 hasn't been released yet. https://hex.pm/packages/dataloader

**Comment by axelson** [comment]
Ah, I see. Oops! Would be nice to have 1.0.3 released since it has some doc updates around the `Dataloader.Ecto` cardinality.
