### ISSUE TITLE
Any way to partition the queries to limit for each branch separately?

### ISSUE THREAD

**Issue by icehaunter** [absinthe-graphql/dataloader#51]
Basically, my question is this:
I want to be able to do the following query in absinthe:
```gql
query {
  categories {
    products(limit: 4) {
      ...
    }
  }
}
```

The resolver for products in the categories is a `dataloader/1` function delegating to the query function, as per the tutorial.

In the `query/2` function I receive the `limit` parameter, as expected, but when I go to limit the query like

```elixir
from p in Product, limit: 4
```

Dataloader gives 4 objects in total, not per category.
How can I get around this limitation?

StackOverflow turned up a couple of solutions like `https://stackoverflow.com/questions/1124603/grouped-limit-in-postgresql-show-the-first-n-rows-for-each-group`, but I really don't know where to plug them.

**Comment by icehaunter** [comment]
For now, I had implemented this behavior using `on_load/2` instead of `dataloader/1`, limiting the results already in Elixir. This isn't optimal, in my opinion, but it works and my database is not that large for now.

```elixir
  object :category do
    field :products, list_of(:product) do
      arg :limit, :integer, description: "Limit the amount of fetched items"
      resolve fn category, %{limit: limit} = args, %{context: %{loader: loader}} ->
        loader
        |> Dataloader.load(Project.Shop, {:products, args}, category)
        |> on_load(fn loader ->
          items =
            loader
            |> Dataloader.get(Project.Shop, {:products, args}, category)
            |> maybe_limit(limit)

          {:ok, items}
        end)
      end
   end
  end

  defp maybe_limit(list, limit) when is_integer(limit) and limit > 0, do: Enum.take(list, limit)
  defp maybe_limit(list, _), do: list
```

**Comment by axelson** [comment]
If you want to do this type of query you need to look into Lateral Join, full support for them requires Ecto 3.0. However, I'm not sure about any examples that directly touches this (relatively common) use-case. But maybe someone else can help you out there.

**Comment by aaparmeggiani** [comment]
Hey @icehaunter,  is this the one you were waiting for?
https://github.com/elixir-ecto/ecto/commit/ec47bb8483dd5206bd02b68c69c15eacf744be07

**Comment by tlvenn** [comment]
This is now supported with the latest release (See https://github.com/absinthe-graphql/dataloader/pull/93)
