### ISSUE TITLE
Calling Dataloader.get on a value that wasn't loaded raises an error

### ISSUE THREAD

**Issue by axelson** [absinthe-graphql/dataloader#52]
Writing this up as discussed in our Slack discussion, although I'm not sure it is a bug per se.

I think this may be just a change in behavior that should be documented as a breaking change (in 1.0.3). I'll prepare a PR to that effect.

**Comment by benwilson512** [comment]
Ah yeah definitely not a bug if it wasn't already loaded. Trying to do a `get` for something that wasn't already there was never really supported, it just didn't happen to return an error before.

**Comment by axelson** [comment]
Yup, makes total sense.
