### ISSUE TITLE
Support Ecto 3.0

### ISSUE THREAD

**Issue by cbrewster** [absinthe-graphql/dataloader#56]
When I try to update to Ecto 3.0 in my codebase I get a conflict:
```
Failed to use "db_connection" because
  ecto (versions 2.2.0 to 2.2.11) requires ~> 1.1
  ecto_sql (version 3.0.0) requires ~> 2.0
```

**Comment by axelson** [comment]
That's not related to data loader since dataloader requires specifies any version of ecto `{:ecto, ">= 0.0.0", optional: true}`

Try `mix deps.update ecto db_connection` to update db_connection as well.

**Comment by cbrewster** [comment]
Ahh thanks, Everything seems to work now!
