### ISSUE TITLE
Dataloader.Ecto raises if ID type casting fails

### ISSUE THREAD

**Issue by 1player** [absinthe-graphql/dataloader#71]
https://github.com/absinthe-graphql/dataloader/blob/56f7cb4ceb822f6d75c53188902b32a4cb9b737c/lib/dataloader/ecto.ex#L540

By default the `ID` type in Absinthe is a String. If one has regular integer fields in their Ecto schema, a user might pass a string that can't be casted to ID, the line above will fail, raising an match error.

```
iex(1)> Ecto.Type.cast(:id, "123")
{:ok, 123}
iex(2)> Ecto.Type.cast(:id, "foo")
:error
```

Setting `get_policy` to `:return_nil_on_error` or `:tuples` will still make dataloader raise.

The workaround seems to be checking the id arguments as valid before calling the dataloader, defeating the purpose of the dataloading helpers in `Absinthe.Resolution.Helpers`

**Comment by benwilson512** [comment]
This is probably the correct result right? Ecto would raise as well if you were doing this manually. Silently ignoring the input per the PR doesn't seem like the answer.

**Comment by 1player** [comment]
What's the alternative? Checking if an ID can be parsed as integer in all resolve functions is not very ergonomic, and would introduce unfortunate coupling between the Ecto model and the GraphQL schema.

At this time, any Absinthe GraphQL server that uses dataloader can crash and raise an exception just by passing a string to an `ID` argument, when using the default `Absinthe.Resolution.Helpers` functions and/or example implementations from the documentation.

I'm open to suggestions.

**Comment by benwilson512** [comment]
What I'm suggesting is that this is a general problem you run into when using Ecto inside resolvers, whether that is mediated by dataloader or not. It would seem then that the solution should probably happen at the GraphQL level, whatever that may be.
