### ISSUE TITLE
Transforming Ecto struct

### ISSUE THREAD

**Issue by zdeneksejcek** [absinthe-graphql/dataloader#76]
Hi,

we use Absinthe, Ecto and dataloader to fetch data from DB. In table, we have string column, but in GraphQl interface, we need to present string as enum (with String.to_atom or something).

Is there a place for such a transformation?
Thanks.

**Comment by benwilson512** [comment]
Hey @zdeneksejcek. In the future, general Absinthe questions should probably use the forums or other help channels not the issue tracker.

This doesn't really have anything to do with Dataloader, since you can solve this with your enum definition. Instead of doing:

```
enum :foo do
  value :bar
  value :baz
end
```
Do: 
```
enum :foo do
  value :bar, as: "bar"
  value :baz, as: "baz"
end
```
