### ISSUE TITLE
ORDER BY of a has_many through not respected

### ISSUE THREAD

**Issue by hisapy** [absinthe-graphql/dataloader#78]
Given the following Ecto schema (copied from the tests)

```elixir
schema "posts" do
     belongs_to(:user, Dataloader.User)
     has_many(:likes, Dataloader.Like)
     has_many(:liking_users, through: [:likes, :user])
      field(:title, :string)		     
     
     field(:deleted_at, :utc_datetime)
 end		   
```
and a `query/2` function like 

```elixir
  def query(User, _args) do
    User |> order_by(desc: :id)
  end
```

The end result of 

```elixir
       loader
       |> Dataloader.load(Test, :liking_users, post1)
       |> Dataloader.run()
```

is not not ordered by `user.id` DESC

In other words, the end result is returned with the order of the intermediate query, not honoring the ORDER BY clause given in  `query/2` .

I'm not very familiar with the code but from I've saw in it, it seems to me that instead of keeping intermediate query results for ` %Ecto.Association.HasThrough{through: through}`, these results have to be replaced by the end query in order to respect the given ORDER BY

**Comment by gabrielpra1** [comment]
I'm also experiencing this bug in v1.0.7
