### ISSUE TITLE
Support "max batch size"

### ISSUE THREAD

**Issue by jaslong** [absinthe-graphql/dataloader#79]
Analogous to https://github.com/graphql/dataloader/pull/42

Very useful with the KV source, where the load function is calling batch APIs with max batch sizes.

I may be able to help implement this. If I were to implement to this, should the "max batch size" functionality be in the Dataloader or KV level? I think it makes sense at the Dataloader level to allow any source to use this functionality.

**Comment by benwilson512** [comment]
I think this depends on the source, since whether this limit can even be used depends on the source. PR welcome.
