### ISSUE TITLE
There is no tag `v1.0.6` which is the latest version in hex

### ISSUE THREAD

**Issue by futpib** [absinthe-graphql/dataloader#80]
This complicates investigation and makes all links from hexdocs broken

**Comment by benwilson512** [comment]
Tag added for 1.0.7

**Comment by futpib** [comment]
Still no tag for 1.0.6 so unless you upgrade you can't check the source code for the version you're using on github. All source code links on https://hexdocs.pm/dataloader/1.0.6/Dataloader.html are broken.

**Comment by benwilson512** [comment]
Also now fixed.
