### ISSUE TITLE
Is it possible to specify which field to batch requests by?

### ISSUE THREAD

**Issue by Adzz** [absinthe-graphql/dataloader#85]
This is more of a question, like is it a good idea / possible...

We have a struct that does not always have an id; the struct is generated from a sql query and we map the result into a struct (that might at some point get saved to the db).

That struct also has relations, and I was going to use dataloader to get its relations, but dataloader batches by the parent id (as far as I can tell). Meaning if we generate 3 different structs which all have a null id, dataloader says "I've seen this struct before" and thinks all of them are the same thing, when they are not.

Is there a way to tell dataloader to _not_ do that? Can I say "Hey dataloader use these key(s) to batch on"? Is this is a good idea even? Are bagels just doughnuts in disguise??

**Comment by benwilson512** [comment]
Hey @Adzz this is entirely doable. I'll start with the most explicit version and go from there. Most explicitly you can just do this:

```
resolve fn parent, args, %{context: %{loader: loader}} ->
  loader
  |> Dataloader.load(SomeSource, {:one, SomeChild}, some_column: parent.some_value)
  |> on_load(fn loader ->
    value = Dataloader.get(loader, SomeSource, {:one, SomeChild}, some_column: parent.some_value)
    {:ok, value}
  end)
end
```

This will batch get a bunch of SomeChild schemas based on `some_column`. When you say relations though, if you define the relations properly such that `parents |> Ecto.assoc(:children) |> Repo.all` works, then dataloader should just work. Can you provide more details?

**Comment by Adzz** [comment]
Sorry I never managed to get back to this and now I've left the work where the codebase was that had this problem! Thanks for the reply though!
