### ISSUE TITLE
Package release needed that includes merged PR #75

### ISSUE THREAD

**Issue by dpehrson** [absinthe-graphql/dataloader#86]
Howdy all,

We recently ran into a production bug which breaks queries that touch the same field (backed by a custom `KV` store) in two different places in the query.

The underlying bug was fixed in #75 and merged in commit 4c4d53610aeca7561636ba6c97f1c5f633462ed4

Currently we are depending on that commit specifically for builds/deployments, but would greatly appreciate if it would be possible to cut a new release that could be published to hex.

@bruce said to post an issue and tag @benwilson512, so here you go!

Thanks for everything, dataloader is magic.

**Comment by benwilson512** [comment]
Done!
