### ISSUE TITLE
Allow override for preload in Dataloader Ecto

### ISSUE THREAD

**Issue by jfrolich** [absinthe-graphql/dataloader#87]
We can already override `run_batch`, but `preload` is hard coded. It would be nice to be able to add a customizable preload here.

**Comment by benwilson512** [comment]
Hi @jfrolich can you elaborate?

**Comment by jfrolich** [comment]
🙈Can't remember anymore. Sorry for this poorly described issue. I can remember I had some dirty workaround so I will probably run into this later on, and then try to create a better issue.

**Comment by benwilson512** [comment]
All good!
