### ISSUE TITLE
Dataloader.dataloader_timeout/1 returns nil if any source has no timeout specified

### ISSUE THREAD

**Issue by tcrossland** [absinthe-graphql/dataloader#94]
I have a Dataloader with several data sources. Some are slow `Dataloader.KV` sources, so I set their timeouts to 30 seconds. Others are fast `Dataloader.Ecto` sources, I don't specify a timeout. The problem is that `dataloader_timeout/1` return `nil` instead of `30_000`, so the dataloader doesn't respect the timeout of the slow data sources.

I think this is an issue, feel free to close otherwise.

**Comment by benwilson512** [comment]
> Others are fast Dataloader.Ecto sources, I don't specify a timeout.

This is sort of a bug, in that I the `Source.timeout` function should either return a manually specified timeout, or default to the default timeout.

Do note therefore that the way this will be fixed is by _always_ having a timeout specified. If you want something to run indefinitely you can use `timeout: :infinity` but I strongly caution against this.

**Comment by tcrossland** [comment]
> Do note therefore that the way this will be fixed is by always having a timeout specified.

Thanks Ben, that's what I ended up doing. For some reason resolution was still timing out after 17 seconds (rather than the 30 seconds I'd specified in the dataloader and it's sources). I was able to improve the response time of the slow datasources using batching so this is no longer a problem for me, but I suspect a timeout issue remains somewhere in the resolution / dataloader modules. Feel free to close this in any case, if I get time I'll try to reproduce the issue and include further details here.

**Comment by tcrossland** [comment]
I've looked into this a bit further... It seems that `Dataloader.KV.run/1` doesn't pass the `timeout` or `max_concurrency` to `Dataloader.run_tasks/3`.

https://github.com/absinthe-graphql/dataloader/blob/5bdf29472372b369ae3eb2766a975bebc14944de/lib/dataloader/kv.ex#L102-L110

Even if it did pass the options, the `max_concurrency` option is currently ignored by `Dataloader.run_tasks/3`, so the timeout for a KV data source is set to the default value of 15 seconds and concurrency is the default (`System.schedulers_online/0`)

https://github.com/absinthe-graphql/dataloader/blob/5bdf29472372b369ae3eb2766a975bebc14944de/lib/dataloader.ex#L309-L326

This is problematic if the KV data source is backed by a slow or non-concurrent resource.

The good news is it doesn't look TOO tricky to fix, I'll see if I can put together a pull request.

**Comment by tcrossland** [comment]
@benwilson512 thanks for merging #95... I guess this issue can be closed now? Let me know if you'd like me to do a PR to document the `max_concurrency` option.

**Comment by benwilson512** [comment]
More documentation is always better, that'd be great, thanks!
